fix in get_account_hierarchy
googleads/google-ads-python pull request #522
Opened 2021-10-23 13:53 UTC by CefBoud

I had the same error  mentionned in [#441 ](https://github.com/googleads/google-ads-python/issues/441) using code based on `examples/account_management/get_account_hierarchy.py`. 
 
> Error with message "User doesn't have permission to access customer. Note: If you're accessing a client customer, the manager's customer id must be set in the 'login-customer-id' header. See https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid".

The error occurs in the `client.get_service("GoogleAdsService").search` method because the client doesn't have a `login_customer_id `.

Assigning the seed_customer_id (which is part of the accessible customers) to `GoogleAdsClient` that generates `GoogleAdsService` worked for me.
```python
for seed_customer_id in seed_customer_ids:
        client.login_customer_id = str(seed_customer_id)
        googleads_service = client.get_service("GoogleAdsService")

```

2021-11-06 09:32 UTC, CefBoud commented
@googlebot I signed it!

2022-08-23 15:04 UTC, BenRKarl requested changes

2022-08-23 15:04 UTC, BenRKarl commented on examples/account_management/get_account_hierarchy.py
> +        googleads_service = client.get_service("GoogleAdsService")
Seems like the first `googleads_service` initialization on line 43 can be removed, then line 79 can be updated to use customer service: 

```py

customer_id = customer_service.parse_customer_path(
    customer_resource_name
)["customer_id"]
```

2022-11-18 22:03 UTC, ThatsJustCheesy commented
The changes here fixed the example for me. Previously, I was getting "User doesn't have permission to access customer."

The final patched code:

```py
for seed_customer_id in seed_customer_ids:
    client.login_customer_id = seed_customer_id
    googleads_service = client.get_service("GoogleAdsService")
```

using @BenRKarl's suggested changes

2025-04-11 13:28 UTC, closed without merging